export const tabsData = [
  {
    id: 1,
    title: "Dashboard",
    src: "/icons/apps.svg",
    pinned: false,
    url: "/dashboard",
  },
  {
    id: 2,
    title: "Banking",
    src: "/icons/bank.svg",
    pinned: false,
    url: "/banking",
  },
  {
    id: 3,
    title: "Settings",
    src: "/icons/settings.svg",
    pinned: false,
    url: "/settings",
  },
  {
    id: 4,
    title: "Shop",
    src: "/icons/shop.svg",
    pinned: false,
    url: "/shop",
  },
  {
    id: 5,
    title: "Profile",
    src: "/icons/user.svg",
    pinned: false,
    url: "/profile",
  },
  {
    id: 6,
    title: "Cart",
    src: "/icons/cart.svg",
    pinned: false,
    url: "/cart",
  },
  {
    id: 7,
    title: "Book",
    src: "/icons/book.svg",
    pinned: false,
    url: "/book",
  },
  {
    id: 8,
    title: "Browser",
    src: "/icons/browser.svg",
    pinned: false,
    url: "/browser",
  },
  {
    id: 9,
    title: "Cube",
    src: "/icons/cube.svg",
    pinned: false,
    url: "/cube",
  },
  {
    id: 10,
    title: "Phone",
    src: "/icons/phone.svg",
    pinned: false,
    url: "/phone",
  },
  {
    id: 11,
    title: "Mail",
    src: "/icons/mail.svg",
    pinned: false,
    url: "/mail",
  },
];
